import { describe, expect, test } from 'bun:test';
import { access, readFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const read = (path: string) => readFile(new URL(path, root), 'utf8');

describe('launch frontend contracts', () => {
  test('idea authors hydrate through the least-privilege public profile view', async () => {
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const detail = await read('src/components/ideas/IdeaDetail.tsx');
    const ideaLib = await read('src/lib/ideas.ts');
    const feedMigration = await read('supabase/migrations/035_aggregated_post_feed.sql');
    const authorPreview = await read('src/components/ideas/PostAuthorPreview.tsx');
    const authorIdentity = await read('src/components/ideas/PostAuthorIdentity.tsx');
    expect(feed).toContain('listPostFeed(initialView)');
    expect(detail).toContain('attachPublicAuthors');
    expect(ideaLib).toContain(".from('idea_public_authors')");
    expect(ideaLib).toContain('linkedin_url');
    expect(feedMigration).toContain("'profiles', case when author.id is null then null else jsonb_build_object(");
    expect(feedMigration).not.toContain("'author_id'");
    expect(feedMigration).not.toContain("'anonymous_visitor_id'");
    expect(feed).toContain('PostAuthorIdentity');
    expect(detail).toContain('PostAuthorPreview');
    expect(authorPreview).toContain('`/members/${profile.handle}`');
    expect(authorPreview).toContain('group-hover:visible');
    expect(authorPreview).toContain('hidden w-72');
    expect(authorPreview).toContain('sm:block');
    expect(authorPreview).toContain('FaLinkedinIn');
    expect(authorPreview).toContain('FaGithub');
    expect(authorPreview).toContain('FaXTwitter');
    expect(authorPreview).toContain('LuGlobe');
    expect(authorIdentity).toContain('LuGhost');
    expect(authorIdentity).toContain('LuUserRound');
    expect(authorIdentity).toContain('resolveAvatarUrl');
    expect(authorIdentity).toContain('createdAt');
    expect(feed).not.toContain('profiles!ideas_author_id_fkey');
    const admin = await read('src/lib/admin.ts');
    expect(admin).toContain('attachPublicAuthors');
    expect(admin).not.toContain('profiles!ideas_author_id_fkey');
  });

  test('member details use the dedicated profile component', async () => {
    const route = await read('src/pages/members/[handle].astro');
    expect(route).toContain('MemberProfile');
    expect(route).toContain('Astro.params.handle');
    expect(route).not.toContain('MemberDirectory');
  });

  test('mobile navigation and auth-aware controls are wired', async () => {
    const nav = await read('src/components/Nav.astro');
    const footer = await read('src/components/Footer.astro');
    const votingLink = await read('src/components/voting/VotingFeatureLink.tsx');
    const siteSession = await read('src/components/auth/useSiteSession.ts');
    expect(nav).toContain('mobile-menu');
    expect(nav).toContain('AuthStatus client:load');
    expect(nav).toContain('href="/posts"');
    expect(nav).toContain('href="/events"');
    expect(nav).toContain('href="/members"');
    expect(nav.match(/>Posts<\/a>/g)).toHaveLength(2);
    expect(nav.match(/<VotingFeatureLink/g)).toHaveLength(2);
    expect(nav).not.toContain('>Ideas</a>');
    expect(footer).toContain('<VotingFeatureLink className="hover:text-limewash" client:load />');
    expect(siteSession).toContain('getVotingFeatureAccess');
    expect(siteSession).toContain('shouldShowVotingLink(access)');
    expect(votingLink).toContain('useSiteSession');
    expect(votingLink).toContain('if (!votingVisible) return null');
    expect(votingLink).toContain('href="/voting"');
  });

  test('posts use the canonical route, sidebar controls, modal composer, and an author-first mobile feed', async () => {
    const page = await read('src/pages/posts.astro');
    const legacyPage = await read('src/pages/ideas.astro');
    const detailPage = await read('src/pages/posts/[slug].astro');
    const legacyDetailPage = await read('src/pages/ideas/[slug].astro');
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const authorIdentity = await read('src/components/ideas/PostAuthorIdentity.tsx');
    const managementMenu = await read('src/components/ideas/PostManagementMenu.tsx');
    const composer = await read('src/components/ideas/IdeaComposer.tsx');
    const authStatus = await read('src/components/auth/AuthStatus.tsx');
    const settings = await read('src/pages/settings.astro');
    expect(page).toContain('IdeaFeed layout="sidebar"');
    expect(legacyPage).toContain("Astro.redirect(`/posts${Astro.url.search}`");
    expect(detailPage).toContain("publicRecordLookup<PostCardRecord>('ideas', 'slug', slug");
    expect(detailPage).toContain("socialCardPath('post', slug, post.updated_at)");
    expect(legacyDetailPage).toContain("Astro.params.slug ?? ''");
    expect(legacyDetailPage).toContain('Astro.url.search');
    expect(legacyDetailPage).toContain('Astro.redirect(`/posts/${encodeURIComponent');
    expect(feed).toContain('<IdeaComposer tagCatalog={tagCatalog}');
    expect(feed).toContain('aria-label="Post controls"');
    expect(feed).toContain('aria-label="Filter posts"');
    expect(feed).toContain("const refresh = () => void load(false)");
    expect(feed).toContain("layout === 'sidebar' && (loading || error)");
    expect(feed).toContain('PostAuthorIdentity');
    expect(feed.indexOf('PostAuthorIdentity profile={idea.profiles}')).toBeLessThan(feed.indexOf('href={`/posts/${idea.slug}`}'));
    expect(authorIdentity).toContain('h-8 w-8 rounded-full');
    expect(authorIdentity).toContain('items-center gap-2 text-xs');
    expect(feed).toContain('className="divide-y divide-white/10 sm:space-y-5 sm:divide-y-0"');
    expect(feed).toContain('className="text-[1.05rem] font-bold leading-snug text-white transition hover:text-limewash sm:text-xl"');
    expect(feed).toContain('className="line-clamp-3 text-[0.9375rem] leading-6 text-braga-100 sm:line-clamp-4 sm:text-sm"');
    expect(feed).toContain("const tagClass = 'inline-flex min-h-8 items-center rounded-full border border-violet-300/25 bg-violet-500/10 px-2 text-[11px]");
    expect(feed).toContain('<PostManagementMenu');
    expect(feed).toContain('variant="feed"');
    expect(managementMenu).toContain('LuEllipsis');
    expect(managementMenu).toContain('Post options');
    expect(managementMenu).toContain('Edit post');
    expect(managementMenu).toContain('Mark as done');
    expect(managementMenu).toContain('Delete post');
    expect(managementMenu).toContain("document.addEventListener('pointerdown', closeOutside)");
    expect(managementMenu).toContain("document.addEventListener('keydown', closeOnEscape)");
    expect(feed).not.toContain('Your posts are tied to your member profile.');
    expect(composer).toContain('Create a new post');
    expect(composer).toContain('aria-labelledby="post-composer-title"');
    expect(authStatus).toContain('>Dashboard</a>');
    expect(settings).toContain("communityPageTitle('Dashboard')");
  });

  test('post member filters rank active posters, stay avatar-only, and expand beyond six', async () => {
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const memberFilters = await read('src/components/ideas/PostMemberFilters.tsx');
    const ranking = await read('src/lib/postMemberFilters.ts');
    expect(feed).toContain('scopeIdeasToPostView(ideas, view)');
    expect(feed).toContain('rankPostingMembers(viewScopedIdeas)');
    expect(feed).toContain('ideaMatchesMember(idea, selectedMemberHandle)');
    expect(feed).toContain('<PostMemberFilters');
    expect(memberFilters).toContain('collapsedMemberLimit = 6');
    expect(memberFilters).toContain('AvatarImage');
    expect(memberFilters).toContain('role="tooltip"');
    expect(memberFilters).toContain('group-hover:opacity-100');
    expect(memberFilters).toContain('aria-label={`Filter posts by member:');
    expect(memberFilters).toContain("aria-label={expanded ? 'Show fewer member filters' : 'Show all member filters'}");
    expect(ranking).toContain('right.postCount - left.postCount');
    expect(ranking).toContain('if (!profile?.handle) continue');
  });

  test('community voting is feature-gated publicly and organizer-controlled', async () => {
    const page = await read('src/pages/voting.astro');
    const board = await read('src/components/voting/VotingBoard.tsx');
    const adminPage = await read('src/pages/admin/voting.astro');
    const adminDashboard = await read('src/components/admin/AdminDashboard.tsx');
    const manager = await read('src/components/admin/VotingManager.tsx');
    const settings = await read('src/components/admin/CommunityFeatureSettings.tsx');
    const client = await read('src/lib/voting.ts');
    expect(page).toContain('VotingBoard client:load');
    expect(board).toContain('Live results');
    expect(board).toContain('Vote anonymously');
    expect(board).toContain('When unchecked, your member name appears publicly');
    expect(board).toContain('Sign in with your member account');
    expect(board).toContain('Update my vote');
    expect(board).toContain('Create a new poll');
    expect(board).toContain('operations.access()');
    expect(board.indexOf('const rows = await operations.list()')).toBeLessThan(board.indexOf('const access = await operations.access()'));
    expect(board).toContain('canViewCommunityVoting(access)');
    expect(board).toContain('!featureAccess || !canViewVoting');
    expect(board).toContain('Page not found');
    expect(board).toContain('Voting is currently off. Organizers can still review these results.');
    expect(board).toContain('{isAdmin && <a className="btn-primary" href="/admin/voting">Create a new poll</a>}');
    expect(board).toContain('const refresh = useCallback(() => load(false)');
    expect(client).toContain("rpc('get_voting_feature_access'");
    expect(client).toContain("rpc('admin_set_voting_feature_enabled'");
    expect(client).toContain("rpc('list_public_community_votes'");
    expect(client).toContain("rpc('submit_community_ballot'");
    expect(adminPage).toContain('mode="voting"');
    expect(adminDashboard).toContain("mode === 'voting'");
    expect(settings).toContain('role="switch"');
    expect(settings).toContain('setVotingFeatureEnabled');
    expect(manager).toContain('Manage feature availability in Settings');
    expect(manager).not.toContain('setVotingFeatureEnabled');
    expect(manager).toContain('Preview vote');
    expect(manager).toContain('Save draft');
    expect(manager).toContain('Publish vote');
    expect(manager).toContain('Close early');
    expect(manager).toContain('options.length < 10');
  });

  test('super admins control post participation modes', async () => {
    const dashboard = await read('src/components/admin/AdminDashboard.tsx');
    const moderator = await read('src/components/admin/IdeaModerator.tsx');
    const settings = await read('src/components/admin/CommunityFeatureSettings.tsx');
    const manager = await read('src/components/admin/PostParticipationManager.tsx');
    const participation = await read('src/lib/postParticipation.ts');
    expect(dashboard).toContain("const isSuperAdmin = role === 'super_admin'");
    expect(dashboard).toContain('<CommunityFeatureSettings />');
    expect(settings).toContain('<PostParticipationManager />');
    expect(moderator).not.toContain('PostParticipationManager');
    expect(manager).toContain('Allow anonymous posts');
    expect(manager).toContain('Allow posts from logged-out users');
    expect(manager).toContain('Allow anonymous comments');
    expect(manager).toContain('Allow anonymous replies');
    expect(manager).toContain('role="switch"');
    expect(participation).toContain("rpc('super_admin_set_post_participation_setting'");
  });

  test('idea posting offers anonymous or account attribution without losing the draft', async () => {
    const composer = await read('src/components/ideas/IdeaComposer.tsx');
    const draft = await read('src/lib/ideaDraft.ts');
    const votes = await read('src/components/ideas/UpvoteButton.tsx');
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const ideas = await read('src/lib/ideas.ts');
    const callback = await read('src/components/auth/AuthCallback.tsx');
    const events = await read('src/components/events/EventRegistrationForm.tsx');
    const profile = await read('src/components/profile/ProfileForm.tsx');
    expect(composer).not.toContain('AuthRequired');
    expect(composer).toContain('Post anonymously');
    expect(composer).toContain('checked={effectivePostAnonymously}');
    expect(composer).toContain('anonymousChoice?.accountUserId === accountUserId');
    expect(composer).not.toContain('previousSignedIn');
    expect(composer).toContain('disabled={!signedIn || !anonymousPostsAllowed || settingsLoading}');
    expect(composer).toContain('Post with my profile');
    expect(composer).toContain('Create a new post');
    expect(composer).toContain('showModal()');
    expect(composer).toContain('<dialog');
    expect(composer).toContain('Share an idea, resource, or perspective with the community.');
    expect(composer).not.toContain('Add a RIP');
    expect(composer).toContain('RipTaxonomyPicker');
    expect(draft).toContain('local-community-post-draft-v1');
    expect(draft).toContain("legacyDraftKeys = ['braga-idea-draft-v1']");
    expect(draft).toContain("context: 'signin'");
    expect(draft).toContain("next: '/ideas'");
    expect(callback).toContain("'/posts?restoreIdea=1'");
    expect(composer).toContain("if (!draft)");
    expect(composer).toContain('No saved post was found on this browser');
    expect(composer.indexOf("if (!draft)")).toBeLessThan(composer.indexOf("setMessage('Your post is restored"));
    expect(votes).not.toContain('No account needed');
    expect(feed).toContain('Already a member? Sign in by email');
    expect(feed).toContain('Next event:');
    expect(feed).toContain('RIP_CATEGORIES');
    expect(feed).toContain('usePostTagCatalog');
    expect(feed).toContain('categoryFilter');
    expect(feed).toContain('selectedTags');
    expect(feed).toContain('updateOwnIdea');
    expect(feed).toContain("canMarkDone={isAdmin && idea.status !== 'closed'}");
    expect(feed).toContain('deleteIdea');
    expect(ideas).toContain('createAnonymousIdea');
    expect(ideas).toContain("rpc('post_member_anonymous_idea'");
    expect(ideas).toContain('supabase.auth.getSession()');
    expect(events).toContain('isAnonymousUser');
    expect(profile).toContain('isAnonymousUser');
  });

  test('comments load only on post detail, support nested replies, and expose counts in the feed', async () => {
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const detail = await read('src/components/ideas/IdeaDetail.tsx');
    const comments = await read('src/components/ideas/PostComments.tsx');
    const controls = await read('src/components/ideas/PostCommentControls.tsx');
    const commentLib = await read('src/lib/postComments.ts');
    expect(detail).toContain('<PostComments ideaId={idea.id} />');
    expect(feed).not.toContain('listIdeaComments(');
    expect(feed).toContain('listPostFeed(initialView)');
    expect(feed).toContain('href={`/posts/${idea.slug}#comments`}');
    expect(detail).toContain("window.location.hash !== '#comments'");
    expect(detail).toContain("document.getElementById('comments')?.scrollIntoView");
    expect(detail).toContain('}, [idea?.id]);');
    expect(feed).toContain('idea.comment_count ?? 0');
    expect(comments).toContain('buildPostCommentTree(comments)');
    expect(controls).toContain('comment.replies.map((reply) => <CommentCard');
    expect(controls).toContain('onCreateReply(comment.id, body, postAnonymously)');
    expect(controls).toContain('Post anon?');
    expect(controls).toContain("depth <= 3 ? 'pl-2 sm:ml-5 sm:pl-4'");
    expect(comments).toContain('Leave a Comment');
    expect(comments).toContain('composerTriggerRef.current?.focus()');
    expect(comments).toContain('ref={composerTriggerRef}');
    expect(comments).not.toContain('Sort by');
    expect(controls).not.toContain('Award');
    expect(controls).not.toContain('Share');
    expect(comments).toContain("access === 'active'");
    expect(comments).toContain('sign in required');
    expect(comments).toContain('toggleIdeaCommentUpvote');
    expect(commentLib).toContain("rpc('list_idea_comments'");
    expect(commentLib).toContain("rpc('create_idea_comment'");
    expect(commentLib).toContain("rpc('toggle_idea_comment_upvote'");
  });

  test('post tags are popularity-ranked, expandable, multi-filterable, and member-creatable', async () => {
    const picker = await read('src/components/ideas/RipTaxonomyPicker.tsx');
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const catalog = await read('src/components/ideas/usePostTagCatalog.ts');
    const ideas = await read('src/lib/ideas.ts');
    expect(picker).toContain('collapsedTagLimit = 6');
    expect(picker).toContain('ADD A TAG {createdCount}/{tagLimit}');
    expect(picker).toContain('catalog.slice(0, collapsedTagLimit)');
    expect(picker).toContain('LuChevronDown');
    expect(picker).toContain('LuInfo');
    expect(picker).toContain('createPostTag');
    expect(picker).toContain('tags.length >= 6');
    expect(picker).toContain('const canCreateForPost = canCreate && tags.length < 6');
    expect(picker).toContain('disabled={creating}');
    expect(picker).toContain('Members can create up to 3 tags');
    expect(feed).toContain('collapsedTagLimit = 6');
    expect(feed).toContain('selectedTags.every');
    expect(feed).toContain('aria-label={`Filter posts by category: ${categoryLabel}`}');
    expect(feed).toContain('aria-label={`Filter posts by tag: ${label}`}');
    expect(feed).toContain('aria-pressed={selectedTags.includes(tag)}');
    expect(feed).toContain('LuChevronDown');
    expect(feed).toContain('usage_count');
    expect(catalog).toContain('listPostTags');
    expect(catalog).toContain('community:tags-changed');
    expect(catalog).toContain('existing.length > 0 ? existing : fallbackTags');
    expect(ideas).toContain("rpc('list_post_tags'");
    expect(ideas).toContain("rpc('create_post_tag'");
  });

  test('public events use external RSVP pages without exposing attendee counts', async () => {
    const list = await read('src/components/events/EventList.tsx');
    const detail = await read('src/components/events/EventDetail.tsx');
    const manager = await read('src/components/admin/EventManager.tsx');
    const preview = await read('src/pages/api/event-preview.ts');
    expect(list).not.toContain('registration_count');
    expect(detail).toContain('RSVP on Luma');
    expect(detail).not.toContain('EventRegistrationForm');
    expect(manager).toContain('Publish event');
    expect(list).toContain('See event ↗');
    expect(list).toContain('Past events');
    expect(list).toContain('LuPencil');
    expect(list).toContain('updateEvent');
    expect(preview).toContain("record['@type'] === 'Event'");
  });

  test('the header identity and generic favicon stay configurable', async () => {
    await access(new URL('public/favicon.svg', root));
    await access(new URL('src/pages/404.astro', root));
    const layout = await read('src/layouts/BaseLayout.astro');
    const nav = await read('src/components/Nav.astro');
    const favicon = await read('public/favicon.svg');
    const config = await read('src/config/community.ts');
    const inviteManager = await read('src/components/admin/InviteManager.tsx');
    const dateHelper = await read('src/lib/communityDate.ts');
    expect(layout).toContain('<link rel="icon" href="/favicon.svg"');
    expect(favicon).toContain('<title id="title">Local Community Platform</title>');
    expect(favicon).not.toContain('Braga AI Builders');
    expect(nav).toContain('communityConfig.name.split');
    expect(nav).toContain('bg-limewash font-extrabold');
    expect(nav).not.toContain('/images/braga-brain-network.webp');
    expect(config).toContain("locale: 'en-GB'");
    expect(config).toContain("timeZone: 'Europe/Lisbon'");
    expect(config).toContain("timeZoneLabel: 'Braga time'");
    expect(inviteManager).toContain('`invite-${crypto.randomUUID()');
    expect(inviteManager).not.toContain('`braga-${crypto.randomUUID()');
    expect(dateHelper).toContain('communityConfig.locale');
    expect(dateHelper).toContain('communityConfig.timeZone');
  });

  test('landing and members routes expose only the requested community CTAs', async () => {
    const home = await read('src/pages/index.astro');
    const members = await read('src/components/profile/MemberDirectory.tsx');
    const authStatus = await read('src/components/auth/AuthStatus.tsx');
    const config = await read('src/config/community.ts');
    const footer = await read('src/components/Footer.astro');
    expect(home).toContain('See Posts');
    expect(home).toContain('communityChannel.joinLabel');
    expect(home.match(/data-community-join/g)).toHaveLength(2);
    expect(home).not.toContain('communityConfig.communityChannel.url');
    expect(config).toContain('https://chat.whatsapp.com/YOUR_INVITE_CODE');
    expect(config).toContain('https://github.com/richkapp/local-community-platform');
    expect(config).toContain("tagline: 'A local AI community'");
    expect(config).toContain("heroTitle: 'Curious about AI? Come meet your people.'");
    expect(home).toContain('communityConfig.tagline');
    expect(home).toContain('communityConfig.description');
    expect(home).toContain('communityConfig.home');
    expect(home).toContain('home.heroImage.src');
    expect(home).toContain('home.membershipImage.src');
    expect(home).toContain('home.memoryTitle');
    expect(home).toContain('home.membershipTitle');
    expect(home).not.toContain('/images/braga-aerial-dusk.webp');
    expect(home).not.toContain('/images/bom-jesus-aerial.webp');
    expect(home).not.toContain('/images/braga-brain-network.webp');
    expect(home).not.toContain('class="btn-secondary">Browse Posts');
    expect(config).toContain('Curious about AI? Come meet your people.');
    expect(home).toContain('Anyone can browse posts, publish, and vote without an account.');
    expect(home).not.toContain('How to join');
    expect(authStatus).not.toContain('Use private invite');
    expect(authStatus).toContain('Sign In');
    expect(members).toContain('communityConfig.communityChannel.joinLabel');
    expect(members).toContain('data-community-join');
    expect(members).not.toContain('communityConfig.communityChannel.url');
    expect(config).not.toContain('memberInviteCode');
    expect(config).not.toContain('memberInvitePath');
    expect(footer).toContain('This site is powered by');
    expect(footer).toContain('Local Community Platform');
    expect(footer).toContain('an open-source platform for local communities.');
    expect(footer).toContain('text-limewash underline');
    expect(footer).not.toContain('buymeacoffee.com');
    expect(footer).not.toMatch(/buy the creator a coffee/i);
    expect(footer).toContain('BugReportLauncher client:visible');
    expect(footer).not.toContain('Source code');
    await expect(access(new URL('src/pages/join.astro', root))).rejects.toThrow();
  });

  test('the public bug-report dialog requires useful detail without requiring identity', async () => {
    const dialog = await read('src/components/bug-reports/BugReportDialog.tsx');
    const client = await read('src/lib/bugReports.ts');
    expect(dialog).toContain('Report a bug');
    expect(dialog).toContain('how you found the bug');
    expect(dialog).toContain('required');
    expect(dialog).toContain('minLength={20}');
    expect(dialog).toContain('type="email"');
    expect(dialog).toContain('Optional');
    expect(dialog).toContain('name="website"');
    expect(dialog).toContain('window.location.href');
    expect(dialog).toContain('max-h-[calc(100dvh-2rem)]');
    expect(dialog).toContain('overflow-y-auto');
    expect(client).toContain('/functions/v1/bug-reports');
    expect(client).toContain('getBugReportVisitorId');
  });

  test('email-link sign in and signup stay short, explicit, and passwordless', async () => {
    const page = await read('src/pages/signin.astro');
    const join = await read('src/pages/join/[code].astro');
    const tabs = await read('src/components/auth/SignInTabs.tsx');
    const form = await read('src/components/auth/InviteEmailForm.tsx');
    const steps = await read('src/components/auth/MagicLinkSteps.tsx');
    const retry = await read('src/components/auth/useRetryCountdown.ts');
    const callback = await read('src/components/auth/AuthCallback.tsx');
    const magicLink = await read('src/lib/magicLink.ts');
    const composer = await read('src/components/ideas/IdeaComposer.tsx');
    const composerStatus = await read('src/components/ideas/ComposerMagicLinkStatus.tsx');
    const edge = await read('supabase/functions/request-invite-magic-link/index.ts');
    expect(page).toContain('description={`Sign in to ${communityConfig.name} or get a private invitation to join.`}');
    expect(join).toContain('You’re invited');
    expect(join).toContain('Welcome to {communityConfig.name}');
    expect(join).toContain('{communityConfig.description}');
    expect(join).toContain('Create your account—or sign in—using a magic link.');
    expect(page).toContain('<SignInTabs client:load />');
    expect(page).not.toContain('memberInviteCode');
    expect(tabs).toContain("{ id: 'signin', label: 'Sign In' }");
    expect(tabs).toContain("{ id: 'signup', label: 'Sign Up' }");
    expect(tabs).toContain('role="tablist"');
    expect(tabs).toContain('role="tabpanel"');
    expect(tabs).toContain('<InviteEmailForm mode="signin" onSignUp={() => chooseTab(\'signup\', true)} />');
    expect(form).toContain('New here?');
    expect(form).toContain('Sign Up →');
    expect(form).not.toContain('Get an invite from a friend who’s already a member');
    expect(tabs).toContain('Join the community');
    expect(tabs).toContain('Ask a friend');
    expect(tabs).toContain('data-community-join');
    expect(tabs).not.toContain('href={communityConfig.communityChannel.url}');
    expect(tabs).toContain("['ArrowLeft', 'ArrowRight', 'Home', 'End']");
    expect(form).toContain("{ mode: 'invite'; code: string; onSignUp?: never } | { mode: 'signin'; code?: never; onSignUp: () => void }");
    expect(form).toContain('requestMagicLink');
    expect(form).toContain('const response = await requestMagicLink');
    expect(form).toContain("response.message || 'Request received.");
    expect(magicLink).toContain('/functions/v1/request-invite-magic-link');
    expect(steps).toContain('No password needed');
    expect(steps).toContain('Enter email');
    expect(steps).toContain('Open email');
    expect(steps).toContain('Tap the link');
    expect(form).toContain('MagicLinkSteps');
    expect(form).toContain('Send sign-in link');
    expect(form).toContain('Send magic link');
    expect(form).toContain('create your account or sign in');
    expect(form).not.toContain('This invite creates one member account.');
    expect(form).toContain('useRetryCountdown');
    expect(form).toContain('startRetryCountdown();');
    expect(form).toContain('Send magic link again');
    expect(form).toContain('`Send again in ${retrySeconds}s`');
    expect(form).toContain("status === 'success' && retrySeconds > 0");
    expect(retry).toContain('MAGIC_LINK_RETRY_SECONDS = 60');
    expect(retry).toContain('Math.ceil((retryAt - now) / 1000)');
    expect(form).toContain("I agree to receive the magic link to sign in,{' '}");
    expect(form).toContain('New here?');
    expect(form).toContain('Sign Up →');
    expect(form).not.toContain('data-community-join');
    expect(form).not.toContain('href={communityConfig.communityChannel.url}');
    expect(form).toContain('border-limewash/35 bg-limewash/[0.08]');
    expect(form).not.toContain('sent through Supabase');
    expect(form).toContain('emailConsent: true');
    expect(form).toContain('required');
    expect(composer).toContain('Already a member? Sign in');
    expect(composer).toContain('Membership is invite-only.');
    expect(composer).toContain('communityConfig.communityChannel.joinLabel');
    expect(composer).toContain('someone you know who’s already a member for an invite');
    expect(composer).not.toContain('Anonymous posting is required while signed out.');
    expect(composer).toContain('data-community-join');
    expect(composer).not.toContain('href={communityConfig.communityChannel.url}');
    expect(composer).not.toContain('Create account and post');
    expect(composer).toContain('Sign in to finish your post');
    expect(composer).toContain('MagicLinkSteps');
    expect(composer).toContain('Send sign-in link');
    expect(composer).toContain('useRetryCountdown');
    expect(composer).toContain('requestComposerSignInLink');
    expect(composer).toContain('const responseMessage = await requestIdeaSignIn(email);');
    expect(composer).toContain('setMessage(responseMessage);');
    expect(composer).toContain("const [emailError, setEmailError] = useState('');");
    expect(composer).toContain('error={emailError}');
    expect(composerStatus).toContain('role="alert">{error}');
    expect(composer).toContain("'Request received'");
    expect(composerStatus).toContain('Send magic link again');
    expect(composerStatus).toContain('`Send again in ${retrySeconds}s`');
    expect(composer).toContain("I agree to receive the magic link to sign in,{' '}");
    expect(composer).toContain('href="/terms">Terms and Conditions</a>');
    expect(composer).toContain('href="/privacy">Privacy Policy</a>');
    expect(composer).not.toContain('sent through Supabase');
    expect(composer).toContain('emailBusy || !emailConsent');
    expect(composer).toContain("onClick={() => setStage('form')} disabled={emailBusy}");
    expect(callback).toContain('Finishing sign in…');
    expect(callback).toContain('Send a new sign-in link');
    expect(edge).toContain("payload.context === 'signin'");
    expect(edge).toContain('create_user: false');
    expect(edge).toContain('message: maskedSigninMessage');
    expect(edge).toContain('createUpstreamError(body, response.status)');
    expect(edge).toContain('publicInviteDeliveryError(caught)');
    expect(edge).not.toContain('a sign-in link is on its way');
    expect(edge).not.toContain('IDEA_SIGNUP_INVITE_CODE');
  });

  test('member settings expose five rolling shareable invitation URLs', async () => {
    const settings = await read('src/pages/settings.astro');
    const hub = await read('src/components/settings/SettingsHub.tsx');
    const component = await read('src/components/invites/MemberInvitePool.tsx');
    const invites = await read('src/lib/invites.ts');
    const callback = await read('src/components/auth/AuthCallback.tsx');
    expect(settings).toContain('SettingsHub');
    expect(settings).toContain('<SettingsHub initialTab={initialTab} client:load />');
    expect(hub).toContain('MemberInvitePool');
    expect(component).toContain('Invite friends');
    expect(component).toContain('navigator.share');
    expect(component).toContain('communityConfig.name');
    expect(component).not.toContain("title: 'Join Braga AI Builders'");
    expect(component).toContain('Copy link');
    expect(component).toContain('Available');
    expect(component).toContain('Claim in progress');
    expect(component).toContain('Recently joined');
    expect(component).toContain('requestSequence.current');
    expect(component).toContain("document.visibilityState === 'visible'");
    expect(invites).toContain("rpc('get_my_member_invites'");
    expect(callback).toContain("rpc('claim_my_pending_invite'");
    expect(callback).toContain("inviteFlow !== 'rolling_v1'");
    expect(callback).toContain('if (!recentlyCreated) return');
    expect(callback).toContain("console.error('[invite-claim-backup]'");
  });

  test('member settings explain invitation claim reservations precisely', async () => {
    const component = await read('src/components/invites/MemberInvitePool.tsx');
    const admin = await read('src/components/admin/InviteManager.tsx');
    expect(component).toContain('Claim in progress');
    expect(component).toContain('reserved for up to 24 hours');
    expect(component).toContain('after they request their authentication email');
    expect(component).not.toContain("pending ? 'Pending'");
    expect(admin).toContain("invite.status === 'pending' ? 'Claim in progress'");
  });

  test('settings and posts expose member post history and private bookmark libraries', async () => {
    const settings = await read('src/pages/settings.astro');
    const hub = await read('src/components/settings/SettingsHub.tsx');
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const detail = await read('src/components/ideas/IdeaDetail.tsx');
    const bookmark = await read('src/components/ideas/BookmarkButton.tsx');
    const ideas = await read('src/lib/ideas.ts');
    const feedMigration = await read('supabase/migrations/035_aggregated_post_feed.sql');

    expect(settings).toContain('SettingsHub');
    expect(settings).toContain('<SettingsHub initialTab={initialTab} client:load />');
    expect(settings).toContain("Astro.url.searchParams.get('tab')");
    expect(hub).toContain("'Profile'");
    expect(hub).toContain("'Invites'");
    expect(hub).toContain("'My posts'");
    expect(hub).toContain("'My bookmarks'");
    expect(hub).toContain("searchParams.get('tab')");
    expect(hub).toContain('useState<SettingsTab>(initialTab)');
    expect(hub).toContain("aria-current={activeTab === key ? 'page' : undefined}");
    expect(hub).toContain("navigate(url.href, { history: 'push' })");
    expect(hub).toContain('sync();');
    expect(hub).toContain('IdeaFeed');
    expect(feed).toContain('useState<PostFeedView>(initialFilters.view)');
    expect(feed).toContain('My posts');
    expect(feed).toContain('My bookmarks');
    expect(feedMigration).toContain("'viewer_is_author'");
    expect(feedMigration).toContain("'viewer_has_bookmarked'");
    expect(feedMigration).toContain("'viewer_bookmarked_at'");
    expect(feed).toContain('BookmarkButton');
    expect(feed).toContain('updateOwnIdea');
    expect(feed).toContain('Member access unavailable');
    expect(feed).toContain("setCategoryFilter('all')");
    expect(feed).toContain('listPostFeed(initialView)');
    expect(detail).toContain('BookmarkButton');
    expect(detail).toContain('Bookmarking is unavailable because this account’s community membership is not active.');
    expect(bookmark).toContain('setIdeaBookmark');
    expect(bookmark).toContain('Sign in to bookmark');
    expect(bookmark).toContain('role="alert"');
    expect(bookmark).not.toContain('className="sr-only" role="alert"');
    expect(ideas).toContain("rpc('get_my_post_relationships'");
    expect(ideas).toContain('target_idea_id: ideaId');
    expect(ideas).toContain("rpc('set_idea_bookmark'");
  });

  test('profile directory visibility is a prominent first setting', async () => {
    const form = await read('src/components/profile/ProfileForm.tsx');
    expect(form).toContain('bg-violet-500/15');
    expect(form).toContain('LuEye');
    expect(form.indexOf('Show my profile in the member directory')).toBeLessThan(form.indexOf('Display name'));
  });

  test('profile photos use the native upload flow instead of editable external URLs', async () => {
    const form = await read('src/components/profile/ProfileForm.tsx');
    const uploader = await read('src/components/profile/AvatarUploader.tsx');
    const avatar = await read('src/lib/avatar.ts');
    expect(form).toContain('AvatarUploader');
    expect(form).not.toContain('Avatar image URL');
    expect(form).not.toContain('id="avatar_url"');
    expect(uploader).toContain('AVATAR_SOURCE_MAX_LABEL');
    expect(uploader).toContain('Replace photo');
    expect(uploader).toContain('Remove');
    expect(uploader).toContain('JPEG, PNG, WebP, HEIC, or HEIF');
    expect(uploader).toContain('accept="image/jpeg,image/png,image/webp,image/heic,image/heif,image/heic-sequence,image/heif-sequence,.heic,.heif"');
    expect(avatar).toContain("import('heic-to/csp')");
    expect(avatar).toContain("type: 'bitmap'");
    expect(avatar).toContain('release: () => bitmap.close()');
    expect(avatar).toContain('AVATAR_OUTPUT_SIZE = 384');
    expect(avatar).toContain("contentType: 'image/webp'");
    expect(avatar).toContain("cacheControl: '3600'");
  });

  test('post detail returns to the exact filtered posts view', async () => {
    const postsPage = await read('src/pages/posts.astro');
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const detail = await read('src/components/ideas/IdeaDetail.tsx');
    const navigation = await read('src/lib/postFeedNavigation.ts');

    expect(postsPage).toContain('persistFilters');
    expect(feed).toContain('buildPostFeedPath');
    expect(feed).toContain('POSTS_RETURN_STORAGE_KEY');
    expect(feed).toContain("view !== 'all' && libraryAccess === 'signed-out'");
    expect(feed).toContain("view !== 'all' && libraryAccess === 'inactive'");
    expect(detail).toContain('Back to posts');
    expect(detail).toContain('safePostFeedPath');
    expect(navigation).toContain("'/posts'");
  });

  test('member deletion cleans up a native avatar before removing the account', async () => {
    const admin = await read('src/lib/admin.ts');
    const manager = await read('src/components/admin/MemberManager.tsx');
    expect(admin).toContain("supabase.storage.from('avatars').remove([avatarPath])");
    expect(manager).toContain('deleteMember(member.id, member.avatar_path)');
  });

  test('organizer routes cover the complete v1 operations', async () => {
    for (const path of [
      'src/components/admin/InviteManager.tsx',
      'src/components/admin/MemberManager.tsx',
      'src/components/admin/EventManager.tsx',
      'src/components/admin/IdeaModerator.tsx',
      'src/components/admin/BugReportManager.tsx',
      'src/pages/admin/ideas.astro',
      'src/pages/admin/members.astro',
      'src/pages/admin/bug-reports.astro',
      'src/pages/admin/settings.astro'
    ]) await access(new URL(path, root));
    const admin = await read('src/components/admin/AdminDashboard.tsx');
    const manager = await read('src/components/admin/BugReportManager.tsx');
    const members = await read('src/components/admin/MemberManager.tsx');
    const invites = await read('src/components/admin/InviteManager.tsx');
    const adminLib = await read('src/lib/admin.ts');
    expect(admin).not.toContain('registrations');
    expect(admin).toContain("key: 'bug-reports'");
    expect(manager).toContain("['new', 'in_review', 'done']");
    expect(manager).toContain('updateBugReportStatus');
    expect(manager).toContain('savingIds');
    expect(manager).not.toContain('mailto:');
    expect(admin).toContain("role === 'super_admin'");
    expect(admin).toContain('isSuperAdmin={isSuperAdmin}');
    expect(members).toContain('Make admin');
    expect(members).toContain('Suspend member');
    expect(members).toContain('Delete member');
    expect(members).toContain('This cannot be undone.');
    expect(members).toContain("member.role !== 'super_admin'");
    expect(adminLib).toContain("rpc('super_admin_set_member_role'");
    expect(adminLib).toContain("rpc('super_admin_set_member_suspension'");
    expect(adminLib).toContain("rpc('super_admin_delete_member'");
    expect(invites).toContain('max="50"');
    expect(invites).toContain('min="1"');
    expect(invites).toContain('1–50 uses');
    expect(invites).toContain('Member invite links');
    expect(invites).toContain('Replace link');
    expect(adminLib).toContain("rpc('create_admin_invite'");
    expect(adminLib).toContain("rpc('revoke_admin_invite'");
    expect(adminLib).toContain("rpc('list_member_invites_for_admin'");
  });

  test('posts expose native sharing and the global footer carries legal and support links', async () => {
    const feed = await read('src/components/ideas/IdeaFeed.tsx');
    const detail = await read('src/components/ideas/IdeaDetail.tsx');
    const share = await read('src/components/ideas/SharePostButton.tsx');
    const sharing = await read('src/lib/postSharing.ts');
    const footer = await read('src/components/Footer.astro');
    const authForm = await read('src/components/auth/InviteEmailForm.tsx');
    const bugReport = await read('src/components/bug-reports/BugReportDialog.tsx');
    const terms = await read('src/pages/terms.astro');
    const privacy = await read('src/pages/privacy.astro');

    expect(feed).not.toContain('Narrow the feed without losing your place.');
    expect(feed).toContain('<SharePostButton slug={idea.slug} title={idea.title} variant="feed" />');
    expect(detail).toContain('<SharePostButton slug={idea.slug} title={idea.title} />');
    expect(share).toContain("import { LuForward } from 'react-icons/lu'");
    expect(share).toContain("import { sharePost } from '@/lib/postSharing'");
    expect(share).toContain('aria-label={`Share ${title}`}');
    expect(sharing).toContain('if (client.share)');
    expect(sharing).toContain('client.clipboard.writeText');
    expect(sharing).toContain("caught.name === 'AbortError'");
    expect(footer).toContain('id="site-support"');
    expect(footer).toContain('href="/terms"');
    expect(footer).toContain('href="/privacy"');
    expect(footer.indexOf('aria-label="Footer navigation"')).toBeLessThan(footer.indexOf('aria-label="Legal and support"'));
    expect(footer.indexOf('href="/privacy"')).toBeLessThan(footer.indexOf('<BugReportLauncher'));
    expect(authForm).toContain('href="/terms"');
    expect(authForm).toContain('href="/privacy"');
    expect(bugReport).toContain('href="/privacy"');
    expect(terms).toContain('Terms and Conditions');
    expect(terms).toContain('href="/privacy"');
    expect(terms).toContain('communityConfig.name');
    expect(privacy).toContain('communityConfig.legal');
    expect(privacy).toContain('Operators of forks must review and replace');
    expect(terms).not.toContain('Braga AI Builders');
    expect(privacy).not.toContain('Braga AI Builders');
  });
});
